services:
    oai-nr-ue:
        image: oai-nr-ue:w48
        logging:
           options:
              max-file: "1"
        network_mode: host
        container_name: oai-nr-ue
        command: "numactl --cpunodebind=0 --membind=0 /opt/oai-nr-ue/bin/nr-uesoftmodem"
        privileged: true
        cpuset: 2,4,6,8,10,12,14,16
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
            - SYS_NICE   # for performance
            - IPC_LOCK   # for memory locking
            - SYS_PTRACE # for debugging
        devices:
             - /dev/net/tun:/dev/net/tun
        ulimits:
          core: -1 # for core dumps
          #entrypoint: /bin/bash -c "sleep infinity"
        environment:
            TZ: Europe/Paris
            DISPLAY: $DISPLAY
            USE_ADDITIONAL_OPTIONS: |
               --thread-pool 2,4,6,8,10,12
               --usrp-args type=x4xx,addr=192.168.10.2,mgmt_addr=10.31.66.220,clock_source=external,time_source=external --ue-rxgain 25
               --ue-nb-ant-tx 1
               --ue-nb-ant-rx 1
               --log_config.global_log_options level,wall_clock,nocolor
               --ssb 1478 -r 273 --numerology 1 --band 78 -C 3750000000
               --ue-txgain 0
               --uicc0.imsi 001010000000003
               --ue-fo-compensation -A 90
               --usrp-tx-thread-config 1
           # Unused options: 
              #--T_stdout 2
           #   --usrp-tx-thread-config 1
           # --log_config.mac_log_level debug
           #  --log_config.nr_mac_log_level debug
           # --usrp-tx-thread-config 1 -d
           # --ssb 1478 -r 273 --numerology 1 --band 78 -C 3750000000 --sa
           # --ssb 1528 -r 273 --numerology 1 --band 48 -C 3649140000 --sa
        volumes:
            - ../../conf_files/ue.sa.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ${HOME}/.Xauthority:/root/.Xauthority:rw
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /var/log/aerial/:/var/log/aerial/
            - ~/2024.w48:/oai-ran:ro
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
